# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/ui_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 640)
        MainWindow.setStyleSheet("#mainWidget {\n"
"    border-radius: 5px;\n"
"    background-color: #0f0e13;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: brown;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"    /*border: 3px solid white; */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border: 1px solid red;\n"
"    border-radius: 3px;\n"
"}\n"
"/* ---------| PROCESS PAGE |--------- */\n"
"#processPage {\n"
"    background-color: #0f0e13;\n"
"}\n"
"\n"
"#searchFrame {\n"
"    background: transparent;\n"
"    border: 1px solid rgb(64, 66, 72);\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"#lineEditSearch {\n"
"    background: transparent;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-right: 1px solid rgb(64, 66, 72);\n"
"}\n"
"#searchButtonIcon {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"#labelError {\n"
"    color: rgb(192, 28, 40)\n"
"}\n"
"\n"
"/* ---------| DETAILS FRAME |--------- */\n"
"\n"
"QDockWidget {\n"
"    \n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    width: 3px;\n"
"    background-color: rgb(64, 66, 72);\n"
"}\n"
"\n"
"#dockWidgetContents,  #rightFrame {\n"
"    background-color: #23242a;\n"
"}\n"
"\n"
"#scrollAreaWidgetContents {\n"
"    background: #23242a;\n"
"    border: 3px solid rgb(64, 66, 72);\n"
"    border-bottom: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"#titleFrame {\n"
"    border: 3px solid rgb(64, 66, 72);\n"
"    border-top: none;\n"
"    border-left: none;    \n"
"    border-right: none;\n"
"}\n"
"\n"
"#detailFrameOption QPushButton {\n"
"    background: transparent;\n"
"    border: 2px solid rgb(64, 66, 72);\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"    font: italic 13pt \"Droid Sans Fallback\";;\n"
"    padding: 4px 10px;\n"
"}\n"
"\n"
"#detailFrameOption QPushButton:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#buttonTerminate:hover {\n"
"    /*background: #1289A7;*/\n"
"    background: rgba(234, 32, 39, 189);\n"
"}\n"
"\n"
"#buttonSuspend:hover {\n"
"    background-color: rgba(205, 97, 51, 162);\n"
"}\n"
"\n"
"#buttonResume:hover {\n"
"    background-color: rgba(34, 112, 147, 236);\n"
"\n"
"}\n"
"\n"
"#buttonCloseCard {\n"
"    border-radius: 19px;\n"
"    background: transparent;\n"
"    border: 1px solid rgb(64, 66, 72);\n"
"    background-color: #23242a;\n"
"}\n"
"\n"
"#buttonCloseCard:hover {\n"
"    background-color: #2f3640;\n"
"}\n"
"\n"
"#buttonCloseCard:pressed {\n"
"    background-color: #23242a;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/* ****************\n"
"     MENU FRAME \n"
"**************************/\n"
"\n"
"#leftMenuFrame {\n"
"    background-color: #151419;\n"
"    border-radius: 12px;\n"
"    border: 2px solid #151419;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton {\n"
"    font: italic 13pt \"Droid Sans Fallback\";\n"
"    background-color: transparent;\n"
"    padding: 15px 20px;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:hover {\n"
"    background-color: #0f0e13;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:pressed {\n"
"    background-color: #151419;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:checked {\n"
"    background-color: #0f0e13;\n"
"}\n"
"\n"
"#leftMenuFrame #buttonUsername {\n"
"    font-size: 12pt;\n"
"    background-color: rgba(34, 112, 147, 236);\n"
"    border-radius: 42px;\n"
"    padding: 5px;\n"
"}\n"
"/* ------- Global ---------*/\n"
"\n"
"QLabel {\n"
"    font: italic 12pt \"Droid Sans Fallback\";\n"
"    color: #ffffff;\n"
"}\n"
"/*----------------> QComboBox <---------------------*/\n"
"\n"
"QComboBox {\n"
"    font: italic 12pt \"Droid Sans Fallback\";\n"
"    background-color: #353b48;\n"
"    color: #ffffff;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(64, 66, 72);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    combobox-popup: 0;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: (:/icons/icurlons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #4b7bec; /*rgb(255, 121, 198);    */\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 5px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/*----------------> QTableWidget <---------------------*/\n"
"\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    selection-color: #eeeeee;\n"
"    color: #eeeeee;\n"
"    gridline-color: #2c2d33;\n"
"    border-radius: 2;\n"
"    font: italic 13pt \"Droid Sans Fallback\";;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    font-size: 11pt;\n"
"    color: #eeeeee;\n"
"    /*padding: 6 0 6 -10;*/\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #263848;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #263848;\n"
"    border-width: 1 1 1 0;\n"
"    border-style: solid;\n"
"    border-color: #1b252f;\n"
"    font: 12pt \"Ubuntu Mono\";\n"
"    color: #00d4ff;\n"
"    padding-left:10;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(:(:/icons/icurlons/cil-arrow-top.png));\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(:/icons/icurlons/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"/**************** QScrollBar ****************/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #4b7bec;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #4b7bec;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"/**********************\n"
"    => QScrollBar\n"
"***********************/\n"
"/* \n"
"QScrollBar:vertical {\n"
"    width: 12;\n"
"    margin: 0 0 0 2;\n"
"    border-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: @color01;\n"
"    min-height: 20px;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    border-bottom-right-radius: 2;\n"
"    border-bottom-left-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 12;\n"
"    margin: 2 0 0 0;\n"
"    border-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: @color01;\n"
"    min-width: 20px;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    border-bottom-right-radius: 2;\n"
"    border-bottom-left-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    background: transparent;\n"
"}\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("")
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuFrame = QtWidgets.QFrame(self.mainWidget)
        self.leftMenuFrame.setMinimumSize(QtCore.QSize(255, 0))
        self.leftMenuFrame.setMaximumSize(QtCore.QSize(273, 500))
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonUsername = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUsername.sizePolicy().hasHeightForWidth())
        self.buttonUsername.setSizePolicy(sizePolicy)
        self.buttonUsername.setMinimumSize(QtCore.QSize(85, 85))
        self.buttonUsername.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonUsername.setFont(font)
        self.buttonUsername.setStyleSheet("")
        self.buttonUsername.setIconSize(QtCore.QSize(30, 30))
        self.buttonUsername.setObjectName("buttonUsername")
        self.verticalLayout_2.addWidget(self.buttonUsername, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonProcess = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProcess.sizePolicy().hasHeightForWidth())
        self.buttonProcess.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonProcess.setFont(font)
        self.buttonProcess.setIconSize(QtCore.QSize(30, 30))
        self.buttonProcess.setCheckable(True)
        self.buttonProcess.setChecked(False)
        self.buttonProcess.setObjectName("buttonProcess")
        self.verticalLayout_2.addWidget(self.buttonProcess, 0, QtCore.Qt.AlignHCenter)
        self.buttonService = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonService.sizePolicy().hasHeightForWidth())
        self.buttonService.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.buttonService.setFont(font)
        self.buttonService.setIconSize(QtCore.QSize(30, 30))
        self.buttonService.setCheckable(True)
        self.buttonService.setChecked(False)
        self.buttonService.setObjectName("buttonService")
        self.verticalLayout_2.addWidget(self.buttonService, 0, QtCore.Qt.AlignHCenter)
        self.buttonMachineInfo = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMachineInfo.sizePolicy().hasHeightForWidth())
        self.buttonMachineInfo.setSizePolicy(sizePolicy)
        self.buttonMachineInfo.setIconSize(QtCore.QSize(30, 30))
        self.buttonMachineInfo.setObjectName("buttonMachineInfo")
        self.verticalLayout_2.addWidget(self.buttonMachineInfo, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.leftMenuFrame)
        self.containerStackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        self.containerStackedWidget.setMinimumSize(QtCore.QSize(390, 0))
        self.containerStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.containerStackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerStackedWidget.setObjectName("containerStackedWidget")
        self.processPage = QtWidgets.QWidget()
        self.processPage.setObjectName("processPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.processPage)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.processPage)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelProcessCount = QtWidgets.QLabel(self.frame)
        self.labelProcessCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelProcessCount.setFont(font)
        self.labelProcessCount.setText("")
        self.labelProcessCount.setObjectName("labelProcessCount")
        self.horizontalLayout_3.addWidget(self.labelProcessCount)
        spacerItem2 = QtWidgets.QSpacerItem(234, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.searchFrame = QtWidgets.QFrame(self.frame)
        self.searchFrame.setMinimumSize(QtCore.QSize(260, 0))
        self.searchFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_4.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditSearch = QtWidgets.QLineEdit(self.searchFrame)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Sans")
        font.setPointSize(14)
        self.lineEditSearch.setFont(font)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout_4.addWidget(self.lineEditSearch)
        self.searchButtonIcon = QtWidgets.QPushButton(self.searchFrame)
        self.searchButtonIcon.setMinimumSize(QtCore.QSize(25, 30))
        self.searchButtonIcon.setText("")
        self.searchButtonIcon.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon.setObjectName("searchButtonIcon")
        self.horizontalLayout_4.addWidget(self.searchButtonIcon)
        self.horizontalLayout_3.addWidget(self.searchFrame)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.processPage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.processByUser = QtWidgets.QComboBox(self.frame_4)
        self.processByUser.setMinimumSize(QtCore.QSize(200, 0))
        self.processByUser.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.processByUser.setFont(font)
        self.processByUser.setObjectName("processByUser")
        self.processByUser.addItem("")
        self.processByUser.addItem("")
        self.processByUser.addItem("")
        self.processByUser.addItem("")
        self.horizontalLayout_7.addWidget(self.processByUser)
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.labelError = QtWidgets.QLabel(self.processPage)
        self.labelError.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.verticalLayout_4.addWidget(self.labelError)
        self.processTableWidget = QtWidgets.QTableWidget(self.processPage)
        self.processTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.processTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.processTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.processTableWidget.setObjectName("processTableWidget")
        self.processTableWidget.setColumnCount(3)
        self.processTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.processTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.processTableWidget.setHorizontalHeaderItem(2, item)
        self.processTableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.processTableWidget.horizontalHeader().setHighlightSections(False)
        self.processTableWidget.horizontalHeader().setStretchLastSection(True)
        self.processTableWidget.verticalHeader().setVisible(False)
        self.processTableWidget.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.processTableWidget)
        self.containerStackedWidget.addWidget(self.processPage)
        self.servicePage = QtWidgets.QWidget()
        self.servicePage.setObjectName("servicePage")
        self.frame_2 = QtWidgets.QFrame(self.servicePage)
        self.frame_2.setGeometry(QtCore.QRect(90, 220, 120, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.containerStackedWidget.addWidget(self.servicePage)
        self.horizontalLayout.addWidget(self.containerStackedWidget)
        self.verticalLayout.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rightFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.rightFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.rightFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = QtWidgets.QFrame(self.rightFrame)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCloseCard = QtWidgets.QPushButton(self.titleFrame)
        self.buttonCloseCard.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonCloseCard.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonCloseCard.setText("")
        self.buttonCloseCard.setIconSize(QtCore.QSize(25, 25))
        self.buttonCloseCard.setObjectName("buttonCloseCard")
        self.horizontalLayout_2.addWidget(self.buttonCloseCard)
        self.label = QtWidgets.QLabel(self.titleFrame)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.detailFrameOption = QtWidgets.QFrame(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailFrameOption.sizePolicy().hasHeightForWidth())
        self.detailFrameOption.setSizePolicy(sizePolicy)
        self.detailFrameOption.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.detailFrameOption.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailFrameOption.setObjectName("detailFrameOption")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.detailFrameOption)
        self.horizontalLayout_5.setContentsMargins(5, -1, 6, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonTerminate = QtWidgets.QPushButton(self.detailFrameOption)
        self.buttonTerminate.setIconSize(QtCore.QSize(23, 23))
        self.buttonTerminate.setObjectName("buttonTerminate")
        self.horizontalLayout_5.addWidget(self.buttonTerminate)
        self.buttonSuspend = QtWidgets.QPushButton(self.detailFrameOption)
        self.buttonSuspend.setIconSize(QtCore.QSize(23, 23))
        self.buttonSuspend.setObjectName("buttonSuspend")
        self.horizontalLayout_5.addWidget(self.buttonSuspend)
        self.buttonResume = QtWidgets.QPushButton(self.detailFrameOption)
        self.buttonResume.setIconSize(QtCore.QSize(23, 23))
        self.buttonResume.setObjectName("buttonResume")
        self.horizontalLayout_5.addWidget(self.buttonResume)
        self.verticalLayout_3.addWidget(self.detailFrameOption, 0, QtCore.Qt.AlignRight)
        self.scrollArea = QtWidgets.QScrollArea(self.rightFrame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 470))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_5.addWidget(self.formFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_8.addWidget(self.rightFrame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonUsername.setText(_translate("MainWindow", "Username"))
        self.buttonProcess.setText(_translate("MainWindow", "Process"))
        self.buttonService.setText(_translate("MainWindow", "Service"))
        self.buttonMachineInfo.setText(_translate("MainWindow", "Machine Info"))
        self.lineEditSearch.setToolTip(_translate("MainWindow", "Search process by Name or PID"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Process By User"))
        self.processByUser.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.processByUser.setItemText(0, _translate("MainWindow", "New Item"))
        self.processByUser.setItemText(1, _translate("MainWindow", "New Item"))
        self.processByUser.setItemText(2, _translate("MainWindow", "New Item"))
        self.processByUser.setItemText(3, _translate("MainWindow", "New Item"))
        self.processTableWidget.setSortingEnabled(True)
        item = self.processTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.processTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.processTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        self.label.setText(_translate("MainWindow", "Details"))
        self.buttonTerminate.setText(_translate("MainWindow", "Terminate"))
        self.buttonSuspend.setText(_translate("MainWindow", "Suspend"))
        self.buttonResume.setText(_translate("MainWindow", "Resume"))
import resource_rc
